version: '3'
volumes:
  postgres_data:
  wdqs_data:
  temp_data:
services:
  mapshaper:
    image: crazycapivara/docker-mapshaper
    ports: 
      - "5555"
    networks:
      - wdqs_conn
  osmupdater:
    build: https://github.com/nickpeihl/docker-osmupdater.git
    networks:
      - postgres_conn
    volumes:
      - wdqs_data:/var/lib/wdqs
      - temp_data:/var/tmp
      - ./:/var/lib/osm2pgsql
    command: /var/lib/osm2pgsql/osmUpdate.sh
    depends_on:
      - postgres
    env_file: .env
  osmregions:
    build: https://github.com/nickpeihl/osm-regions-server.git#dockerize
    ports: 
      - "9978"
    networks: 
      - postgres_conn
      - wdqs_conn
    env_file: .env
    depends_on:
      - wdqs
      - postgres
  wdqs:
    build: https://github.com/nickpeihl/wikidata-query-rdf.git#dockerize
    volumes:
      - wdqs_data:/var/lib/wdqs
      - temp_data:/var/tmp
    ports:
      - "9999"
    networks:
      - wdqs_conn
    env_file: .env
  # wdqs-updater:
  #   build: https://github.com/nickpeihl/wikidata-query-rdf.git#dockerize
  #   entrypoint: runUpdate.sh
  postgres:
    image: "openmaptiles/postgis:2.9"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_conn
    ports:
      - "5432"
    env_file: .env
  web:
    build: https://github.com/nickpeihl/wikidata-query-gui.git#dockerize
    ports:
      - "80"
    networks:
      - wdqs_conn
    depends_on:
      - wdqs
  proxy:
    image: nginx
    volumes: 
      - ./sophox.template:/etc/nginx/conf.d/sophox.template
    ports:
      - "8080:80"
    networks:
      - wdqs_conn
      - postgres_conn
    command: sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/sophox.template > /etc/nginx/conf.d/default.conf && nginx-debug -g 'daemon off;'" 
    env_file: .env
networks:
  postgres_conn:
  wdqs_conn: