version: '3'
volumes:
  postgres_data:
  wdqs_data:
  temp_data:
services:
  wdqs:
    build: https://github.com/sophox/wikidata-query-rdf.git#dockerize
    volumes:
      - wdqs_data:/var/lib/wdqs
      - temp_data:/var/tmp
    ports:
      - "9999"
    networks:
      - wdqs_conn
    env_file: .env
  wdqs-updater:
    build: https://github.com/sophox/wikidata-query-rdf.git#dockerize
    entrypoint: 
      - runUpdate.sh
      - -h
      - http://wdqs:9999
    networks:
      - wdqs_conn
  osm-updater:
    build: https://github.com/nickpeihl/osm2rdf.git#dockerize
    entrypoint:
      - ./runOsmUpdater.sh
      - -c
      - /var/lib/wdqs/rgn_nodes.cache
      - -s
      - dense
    volumes:
      - wdqs_data:/var/lib/wdqs
    networks:
      - wdqs_conn
  mapshaper:
    image: crazycapivara/docker-mapshaper
    ports: 
      - "5555"
    networks:
      - wdqs_conn
  pg-updater:
    image: nickpeihl/osmupdater:latest
    networks:
      - postgres_conn
    volumes:
      - wdqs_data:/var/lib/wdqs
      - temp_data:/var/tmp
      - ./:/var/lib/osm2pgsql
    command: /var/lib/osm2pgsql/osmUpdate.sh
    depends_on:
      - postgres
    env_file: .env
  osmregions:
    image: nickpeihl/osm-regions-server:latest
    ports: 
      - "9978"
    networks: 
      - postgres_conn
      - wdqs_conn
    env_file: .env
    depends_on:
      - postgres
  postgres:
    image: "openmaptiles/postgis:2.9"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_conn
    ports:
      - "5432"
    command: -c 'max_wal_size=5GB'
    env_file: .env
  web:
    image: nickpeihl/sophox-query-gui:dockerize
    ports:
      - "80"
    networks:
      - wdqs_conn
    logging:
      driver: none
  proxy:
    image: nginx
    volumes: 
      - ./sophox.template:/etc/nginx/conf.d/sophox.template
    ports:
      - "80:8080"
    networks:
      - wdqs_conn
      - postgres_conn
    logging:
      driver: none
    depends_on:
      - osmregions
      - mapshaper
      - web
    command: sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/sophox.template > /etc/nginx/conf.d/default.conf && nginx-debug -g 'daemon off;'" 
    env_file: .env
networks:
  postgres_conn:
  wdqs_conn:
